#!/usr/bin/env bash


# Configure your user to execute `yabai --load-sa` as the root user without having to enter a password.
#  https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa


######################################################### Local Variables
# To get the names of all the running applications
# yabai -m query --windows | jq -r '.[].app'

# In case you want to add transparent apps
# apps_transparent="(Neovide|Code|Ghostty)"

  apps_stream="()"
  # This keeps apps always below, seems to be working fine when I switch to other apps
  apps_mgoff_below="(Calculator|iStat Menus|Hammerspoon|BetterDisplay|GIMP|Notes|Activity Monitor|App StoreSoftware Update|TestRig|Gemini|Raycast|OBS Studio|Microsoft Edge|Google Chrome|Cisco Packet Tracer|Stickies|kitty|ProLevel|Photo Booth|Hand Mirror|SteerMouse|remote-viewer|Jitsi Meet|DaVinci Resolve)"

# Apps that I want to always show, even when I have a transparent app focused
# apps_transp_ignore="(kitty)"
# apps_scratchpad="(Udemy|WezTerm)"
# apps_transp_ignore="(kitty|CleanShot X)"

# Apps excluded from window management, so you can resize them and move them around
# This is basically the ignore list

# I had to move them away from normal, because all these apps would stay on top
# of other apps
# apps_mgoff_normal="()"

# This keeps apps always on the top
apps_mgoff_above="()"

#########################################################


# In order to prevent simple-bar freezing upon yabai restart, you'll need to add
# this line at the start of your .yabairc file
# https://www.jeantinland.com/toolbox/simple-bar/documentation/installation/#update-your-yabai-config
osascript -e 'tell application id "tracesOf.Uebersicht" to refresh'

###############################################################################
#                              Excluded apps
###############################################################################

yabai -m rule --add app="^${apps_mgoff_normal}$" manage=off
yabai -m rule --add app="^${apps_mgoff_below}$" manage=off sub-layer=below
yabai -m rule --add app="^${apps_mgoff_above}$" manage=off sub-layer=above

# In case you want to debug and see the contents of a variable
# echo "apps_mgoff_below: ^${apps_mgoff_normal}$" > /tmp/yabai_debug.log

# yabai -m rule --add app="kitty" manage=on position=200:50 size=10:50
# yabai -m rule --add app="^kitty$" manage=off position=100:100 size=80:60
#
#
# ###############################################################################
#                             sub-layer=normal
###############################################################################

# https://github.com/koekeishiya/yabai/issues/1929

# Set all apps to the "normal" sub-layer, otherwise they all start on the "below"
# sub-layer. Doing this fixed the issue I had with floating windows with OBS,
# davinci resolve and other apps where their floating windows would show on top
# of other apps

yabai -m rule --add app=".*" sub-layer=normal

###############################################################################
#                                  Misc
###############################################################################

# global settings
# When I leave youtube or chrome, hammerspoon will move the mouse to the corner

# "mouse_follows_focus on" will move the mouse back to the center, but DISABLE it or it will
# be a nightmare to use iStat Menus
yabai -m config mouse_follows_focus off

# I don't understand what this does, I've enabled and disabled it in the past,
# and still don't get it
# This option as removed https://github.com/koekeishiya/yabai/issues/1887
# yabai -m config window_topmost off

# Configure the layout mode
# "stack" - is what I use, keeps a single app on the front
# "bsp" - binary space partitioning enables automatic tiling (partitioning)
# "float" - default mode, windows are not managed
yabai -m config layout stack
# yabai -m config layout bsp
# yabai -m config layout float

###############################################################################
#                                Defaults
###############################################################################

yabai -m config \
  focus_follows_mouse off \
  window_origin_display default \
  window_placement second_child \
  window_zoom_persist on \
  window_shadow off \
  window_animation_duration 2 \
  window_animation_frame_rate 120 \
  window_opacity_duration 0.0 \
  insert_feedback_color 0xffd75f5f \
  active_window_border_color 0xff775759 \
  normal_window_border_color 0xff555555 \
  window_border_width 4 \
  window_border_radius 12 \
  window_border_blur off \
  window_border_hidpi on \
  window_border off \
  split_ratio 0.50 \
  split_type auto \
  auto_balance off \
  window_gap 06 \
  mouse_modifier fn \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap

# THIS IS VERY IMPORTANT
# It ensures that when I restart yabai, all the rules (including the manage=off rules)
# are reapplied to existing windows
# Otherwise yabai takes care of management and I couldnt resize apps like
# packet tracer for example
yabai -m rule --apply
